import { Col, Container, Row } from "react-bootstrap"
import { useNavigate } from "react-router-dom"

export const PrivacyPolicy = () => {
    const navigate = useNavigate()

    return (
        <Container>
            <Row className="d-flex justify-content-center p-5">
                <img src="/heavenscope-high-resolution-logo-transparent.png" alt="heavenscopes-logo" className="login-page-logo" role='button' onClick={() => navigate('/feed')} />
            </Row>

            <Row className="pt-3">
                <Col sm={12}>
                    <h3 className="text-center">Privacy Policy</h3>
                </Col>

                <Col sm={12} className="pt-3">
                    <p>Effective date: Dec. 10, 2024</p>
                    <p>This Privacy Policy outlines how Heavenscopes collects, uses, and protects your personal information when you use our platform. By creating an account and using the service, you agree to the terms described here.</p>
                    <ol className="d-flex flex-column gap-3">
                        <li>
                            <h5>Data We Collect:</h5>
                            <p>We collect the following types of data:</p>
                            <ul>
                                <li>
                                    <h6>User-provided Informations:</h6>
                                    <ul className="pb-3">
                                        <li>Registration data: username, email and crypted password (we do not have direct access to your password).</li>
                                        <li>Profile information: profile picture, bio and account settings (preferred unit system, location data including elevation).</li>
                                    </ul>
                                </li>

                                <li>
                                    <h6>Content Generated by Users:</h6>
                                    <p>Posts, comments, uploaded media.</p>
                                </li>

                                <li>
                                    <h6>Social Interaction:</h6>
                                    <p>Followers and following lists, likes on posts and media.</p>
                                </li>
                            </ul>
                        </li>

                        <li>
                            <h5>How We Use Your Data:</h5>
                            <p>We use your data for the following purposes:</p>
                            <ul>
                                <li>Observation Data: your location and elevation are used to provide accurate celestial observation data, such as the position of planets in the sky.</li>
                                <li>Social Interactions: posts, comments, media, likes and follower/following information are used to enable community interactions and improve user engagement.</li>
                            </ul>
                        </li>

                        <li>
                            <h5>Data Storage and Sharing</h5>
                            <ul>
                                <li>Your data is securely stored in databases, and we do not share it with third parties.</li>
                                <li>Note: The observation API we use may collect location data; however, this data is not linked to your identity.</li>
                            </ul>
                        </li>

                        <li>
                            <h5>Third-Party Services</h5>
                            <p>Heavenscopes uses external services for certain features (e.g., media storage or astronomical data). These services may handle data according to their own privacy policies.</p>
                        </li>

                        <li>
                            <h5>Marketing and Advertising</h5>
                            <p>Heavenscopes does not currently use your data for marketing or advertising purposes.</p>
                        </li>

                        <li>
                            <h5>Data Security</h5>
                            <p>We take reasonable measures to protect your data, including:</p>
                            <ul>
                                <li>Passwords are encrypted before being stored.</li>
                                <li>Authentication tokens are required for all user actions within the platform.</li>
                            </ul>
                        </li>

                        <li>
                            <h5>Contact</h5>
                            <p>Currently, we do not provide a direct contact for privacy inquiries. Updates on this will be provided in future versions of this policy.</p>
                        </li>

                        <li>
                            <h5>Updated to This Policy</h5>
                            <p>This Privacy Policy may be updated from time to time.</p>
                        </li>
                    </ol>
                </Col>
            </Row>
        </Container>
    )
}